### ISSUE TITLE
IDA 9.2 crash when exiting IDA (only with this plugin installed and no crash when plugin is removed)

### ISSUE THREAD

**Issue by Harding-Stardust** [eset/ipyida#78]
When I start IDA with Ipyida I get the message:
```A known critical bug in PySide6 6.8.0 will cause your application to crash. See https://github.com/spyder-ide/qtpy/issues/494```

When I exit IDA 9.2, it crashes.

When running without this plugin, IDA works as expected

Running Windows 10, Python 3.10.5 (installed by IDA installer) with PySide 6.8.0 (installed by IDA installer)

pip list:
```
annotated-types           0.7.0
asttokens                 3.0.0
attrs                     25.3.0
colorama                  0.4.6
comm                      0.2.3
debugpy                   1.8.17
decorator                 5.2.1
exceptiongroup            1.3.0
executing                 2.2.1
fastjsonschema            2.21.2
ipyida                    2.2
ipykernel                 6.29.5
ipython                   8.37.0
ipython_pygments_lexers   1.1.1
jedi                      0.19.2
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
jupyter-client            6.1.12
jupyter_core              5.8.1
matplotlib-inline         0.1.7
nbformat                  5.10.4
nest-asyncio              1.6.0
packaging                 25.0
parso                     0.8.5
pip                       25.2
platformdirs              4.4.0
prompt_toolkit            3.0.52
psutil                    7.1.0
pure_eval                 0.2.3
pydantic                  2.11.9
pydantic_core             2.33.2
Pygments                  2.19.2
python-dateutil           2.9.0.post0
pywin32                   311
pyzmq                     27.1.0
qasync                    0.28.0
qtconsole                 5.7.0
QtPy                      2.4.3
referencing               0.36.2
rpds-py                   0.27.1
setuptools                58.1.0
shiboken6                 6.9.2
six                       1.17.0
stack-data                0.6.3
tornado                   6.5.2
traitlets                 5.14.3
typing_extensions         4.15.0
typing-inspection         0.4.1
wcwidth                   0.2.13
```

**Comment by Harding-Stardust** [comment]
After I got the error, I did run `pip install --upgrade PySide6` but that version that pip installed was not picked up by IDA.
I opened IDA and ran import `PySide6` and then `PySide6.__version__` which gave me version 6.8.0

**Comment by Harding-Stardust** [comment]
Yes, they where only there a short time during testing but it is the same problem before and after. I also updated to the latest MS redistributable but that did not help. I will try to get out a debugger during the weekend.

**Comment by marc-etienne** [comment]
Thanks for checking Igor! I completely missed that import of PyQt5 🤦 . Some else also [spotted it](https://github.com/eset/ipyida/issues/77#issuecomment-3342271819) yesterday. I'll fix this and make a release later today.

I'll find a Windows box to test it too, because that problem doesn't show up on macOS.

**Comment by marc-etienne** [comment]
I've released v2.3 which won't try importing PyQt5.

However, I was _not_ able to reproduce the crash, even on Windows :(. I'm crossing fingers this will

**Comment by marc-etienne** [comment]
Thanks for sharing the crashdump! It will really help find the root cause. It looks really similar to the Linux crash where some Qt object gets (double?) freed (or just its PySide binding?). It will take me some time to dig but I'll try to find which object, likely created by IPyIDA or IPython, is causing the crash.

**Comment by TwoUnderscorez** [comment]
@Harding-Stardust Same here, but only if I run it from IDA's python console. If I run that from IPyIda, it still crashes.
